import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/components/session-provider";
import { headers } from "next/headers";
import { Toaster } from "sonner";
import { DashboardLayout } from "@/components/layout/dashboard-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Onvitech",
  description: "Generated by create next app",
 icons: {
  icon: "/icons/logo.png", 
},
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Get headers - using await if needed
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";
  
  const isAuthPage =
    pathname.startsWith("/login") || 
    pathname.startsWith("/signup") || 
    pathname.startsWith("/reset-password") ||
    pathname.startsWith("/forgot-password");

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <Toaster
            position="top-center"
            theme="light"
            duration={3000}
            toastOptions={{
              className: "custom-toast",
              style: {
                backgroundColor: "#BAEDD7",
                color: "#242B42",
                fontWeight: 500,
                fontSize: "14px",
                border: "none",
              },
            }}
          />
          {isAuthPage ? children : <DashboardLayout>{children}</DashboardLayout>}
        </SessionProvider>
      </body>
    </html>
  );
}