import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/components/session-provider";
import { headers } from "next/headers";
import { Toaster } from "sonner";
import { DashboardLayout } from "@/components/layout/dashboard-layout";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Onvitech",
  description: "Generated by create next app",
  icons: {
    icon: "/Fevicon.png",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";

  const isAuthPage =
    pathname.startsWith("/login") ||
    pathname.startsWith("/signup") ||
    pathname.startsWith("/reset-password") ||
    pathname.startsWith("/forgot-password");

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakarta.variable} font-sans antialiased`}>
        <SessionProvider>
<Toaster
  position="top-center"
  theme="light"
  duration={3000}
/>

          {isAuthPage ? children : <DashboardLayout>{children}</DashboardLayout>}
        </SessionProvider>
      </body>
    </html>
  );
}
